Ui automation
JukinMediaInc/jukin-whatchamacallit pull request #1
Opened 2020-09-05 13:03 UTC by nitishaggarwal11

2020-09-07 15:35 UTC, dprski33 requested changes

2020-09-07 15:35 UTC, dprski33 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
when I run this, I get the following: 
```
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.209 sec <<< FAILURE! - in runner.JukinRunner
runner.JukinRunner  Time elapsed: 0.075 sec  <<< ERROR!
java.lang.IllegalStateException: The driver is not executable: /Users/danriley/jukin-whatchamacallit-nitishaggarwal11/JukinMediaUIAutomation/src/test/resources/chromedriver.exe
	at runner.JukinRunner.initEnvironment(JukinRunner.java:33)

runner.JukinRunner  Time elapsed: 0.075 sec  <<< ERROR!
java.lang.NullPointerException
	at runner.JukinRunner.writeExtentReport(JukinRunner.java:47)
	at runner.JukinRunner.tearDownEnvironment(JukinRunner.java:40)


Results :

Tests in error: 
runner.JukinRunner.runner.JukinRunner
  Run 1: JukinRunner.initEnvironment:33 » IllegalState The driver is not executable: /U...
  Run 2: JukinRunner.tearDownEnvironment:40->writeExtentReport:47 » NullPointer
```

2020-09-07 15:35 UTC, dprski33 commented on JukinMediaUIAutomation/README.md
> +5. If you want to execute the tests on IE or Firefox browser then navigate to \src\main\resources\configuration.properties and change the value of 'browser' property to either IE or Firefox.
is there an easier way to do this? If I wanted to run these tests as part of CI/CD, then I wouldn't want to manually change this

2020-09-07 16:04 UTC, dprski33 commented on JukinMediaUIAutomation/src/test/java/pages/RegisterPage.java
> +	public void clickOnSubmitButton()
Seems like you have this exact same method in 2 places. Is there a better way to organize your code so you aren't copy-pasting?

2020-09-08 13:11 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
It seems to me that you are using Mac OS and you do not have the permissions to access the chromedriver. So, you need to give permission to either complete folder or by chrome executable. Go to \src\test\resources\ folder and execute below 
- chmod 777 chromedriver.exe
OR
- chmod -R 777 {relativePath}\src\test\resources

2020-09-08 13:11 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/README.md
> +5. If you want to execute the tests on IE or Firefox browser then navigate to \src\main\resources\configuration.properties and change the value of 'browser' property to either IE or Firefox.
Yes,  we can run this suite with the help of CI/CD like Jenkins. I have configured it as well and recorded the build and mailing you the Google Drive link for same as the file size is greater than 25MB so I cannot check in into Git. 
We can even configure the browser and other settings as well.

Drive link for CI/CD: https://drive.google.com/file/d/187A55DB6lXctEJ-AGRyKTk-VKE8jzttR/view?usp=sharing

2020-09-08 13:12 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/src/test/java/pages/RegisterPage.java
> +	public void clickOnSubmitButton()
The locator which is being used for clicking on Submit button has different xpath in both the cases. 
Register Page has locator //input[@name='_action_doRegister']
while Forgot Password page has locator //a[@id='forgotPasswordButton']

and the only motive of keeping the Method/Locators of same page in a same class is to achieve Page Object Model.

If we want, we can have a one abstract class having common methods and the pages will extend it but still in that case locators won't be common, it will be specific to page.

2020-09-08 15:15 UTC, dprski33 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
i was able to set the chromedriver path correctly. However, then I encountered this error:
```
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.109 sec <<< FAILURE! - in runner.JukinRunner
runner.JukinRunner  Time elapsed: 3.038 sec  <<< ERROR!
org.openqa.selenium.WebDriverException: 
disconnected: unable to connect to renderer
  (Session info: chrome=85.0.4183.83)
  (Driver info: chromedriver=2.31.488774 (7e15618d1bf16df8bf0ecf2914ed1964a387ba0b),platform=Mac OS X 10.15.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-192-168-0-41.us-west-2.compute.internal', ip: 'fe80:0:0:0:e2:20ed:8bea:3aeb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptSslCerts: true, applicationCacheEnabled: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 2.31.488774 (7e15618d1bf16d..., userDataDir: /var/folders/sr/qcbj8cld4vv...}, cssSelectorsEnabled: true, databaseEnabled: false, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, rotatable: false, setWindowRect: true, takesHeapSnapshot: true, takesScreenshot: true, unexpectedAlertBehaviour: , unhandledPromptBehavior: , version: 85.0.4183.83, webStorageEnabled: true}
Session ID: 89f9aef7ae716d89aa2ff327e4d2b1d5
	at runner.JukinRunner.initEnvironment(JukinRunner.java:33)

runner.JukinRunner  Time elapsed: 3.039 sec  <<< ERROR!
java.lang.NullPointerException
	at runner.JukinRunner.writeExtentReport(JukinRunner.java:47)
	at runner.JukinRunner.tearDownEnvironment(JukinRunner.java:40)


Results :

Tests in error: 
runner.JukinRunner.runner.JukinRunner
  Run 1: JukinRunner.initEnvironment:33 » WebDriver disconnected: unable to connect to ...
  Run 2: JukinRunner.tearDownEnvironment:40->writeExtentReport:47 » NullPointer
```

2020-09-08 15:16 UTC, dprski33 commented on JukinMediaUIAutomation/README.md
> +5. If you want to execute the tests on IE or Firefox browser then navigate to \src\main\resources\configuration.properties and change the value of 'browser' property to either IE or Firefox.
Thank you for including the video. 
If I wanted to use that Jenkins build to run the tests with any of the configured web browsers, what changes would be needed to support that?

2020-09-08 15:19 UTC, dprski33 commented on JukinMediaUIAutomation/src/test/java/pages/RegisterPage.java
> +	public void clickOnSubmitButton()
`we can have a one abstract class`
`achieve Page Object Model`
are these different approaches?

2020-09-09 15:36 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
I guess you are using Mac OS ,I googled around the error which you are getting it seems you have a blank /etc/hosts file, you need to make below entry in this file

127.0.0.1  localhost

If you already having this entry present then the issue is with the Chrome version on your machine, the driver which I am using is not compatible with that. You may need to install the latest Chrome version. Please refer to below link wihch explains this issue

https://stackoverflow.com/questions/46807596/webdrivererror-disconnected-unable-to-connect-to-renderer

2020-09-09 15:37 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/README.md
> +5. If you want to execute the tests on IE or Firefox browser then navigate to \src\main\resources\configuration.properties and change the value of 'browser' property to either IE or Firefox.
Yes, it is possible you just need to pass the browser from maven command line in Jenkins job configuration like: -Dbrowser=ie and then you need to read this System property in code to set the browser.

2020-09-09 15:37 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/src/test/java/pages/RegisterPage.java
> +	public void clickOnSubmitButton()
Approach is similar but the only thing is we generally do not prefer to have a abstract class for 1 function only 
If the application pages contain common component in each page then it would be preferable to a common abstract class and the other page classes would be extending it.

2020-09-09 20:28 UTC, dprski33 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
OK, i updated to a newer chromedriver and got the this result:
```
Failed scenarios:
testFeature.feature:6 # Scenario: Login to the application to view the success message
testFeature.feature:15 # Scenario: To check the Incorrect email/password combination
testFeature.feature:24 # Scenario: To check the Forgot Password Functionality
testFeature.feature:35 # Scenario: To check the invalid email message on Forgot Password Page
testFeature.feature:46 # Scenario: To check the Registration Functionality
testFeature.feature:57 # Scenario: To check the invalid email message on Registration Page
testFeature.feature:68 # Scenario: To check the invalid password confirmation message on Registration Page
testFeature.feature:79 # Scenario: To check the invalid password confirmation message on Registration Page

8 Scenarios (8 failed)
44 Steps (8 failed, 36 skipped)
0m5.238s

org.openqa.selenium.WebDriverException: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: chrome=85.0.4183.83)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-192-168-0-41.us-west-2.compute.internal', ip: 'fe80:0:0:0:e2:20ed:8bea:3aeb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.5', java.version: '1.8.0_202'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 85.0.4183.83, chrome: {chromedriverVersion: 85.0.4183.87 (cd6713ebf92fa..., userDataDir: /var/folders/sr/qcbj8cld4vv...}, goog:chromeOptions: {debuggerAddress: localhost:53524}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}
Session ID: 5b22fd233fc6d1843cd5049555f4c24d
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:277)
	at driver.DriverFactory.navigateToApplication(DriverFactory.java:58)
	at stepDefinition.Login.User_launches_the_Jukin_Media_application(Login.java:20)
	at ✽.Given User launches the Jukin Media application(testFeature.feature:7)
```


is this what I should expect?

2020-09-10 04:17 UTC, nitishaggarwal11 commented on JukinMediaUIAutomation/run-tests.bat
> +echo "Starting project Maven build"
This is not the expected behavior, if you see the Jenkins recording, it's running fine on Windows machine. This seems to be MAC specific issue. Can you try it out on any Windows machine, if possible.

2020-09-23 15:41 UTC, closed without merging