Praveen ui automation script
JukinMediaInc/jukin-whatchamacallit pull request #5
Opened 2020-09-27 19:21 UTC by jaiswalkpraveen

2020-09-28 19:03 UTC, dprski33 commented
In file `AutomatabilityLoginSuggestions.docs` you wrote:
>Allow alternate sign in option with third party social site 

How does this suggestion make our application easier to automate?

2020-09-28 19:15 UTC, dprski33 requested changes

2020-09-28 19:15 UTC, dprski33 commented on grailsUIAutomation/src/main/java/com/grails/managers/WebDriverManager.java
> +	private WebDriver createDriver() {
how might I make use of this feature?

2020-09-28 19:15 UTC, dprski33 commented on grailsUIAutomation/src/main/java/com/grails/pageObjects/RegisterPage.java
> +	Faker faker = new Faker();
these lines are in 3 files. is there another way to do this so that you aren't repeating these lines multiple times?

2020-09-28 19:15 UTC, dprski33 commented on grailsUIAutomation/src/test/java/com/grails/stepDefinitions/Hooks.java
> +	 	      final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
is your framework making use of this?

2020-09-28 19:15 UTC, dprski33 commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/2.Register.feature
> +	    When user enter mailID and password "Fuller@123"
what email is being used in this test?

2020-09-28 19:16 UTC, dprski33 commented on README.md
> +http://localhost:8080/WhatChaMaCallIt should be up and running
Also, it would be nice if there were a way to start the tests and the app at the same time.  This would greatly help with setting up CI/Jenkins

2020-09-29 15:04 UTC, jaiswalkpraveen commented on README.md
> +$ mvn clean install
Dan,
I acknowledge your comment. You can expect resolution by tomorrow.

2020-09-30 13:00 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/1.Login.feature
> +   Scenario Outline: Login into application with invalid credential
login button is not enable if fields are not populated that's why didn't add this test case. If it enable, we can simply add one more data sets in same scenario.

2020-09-30 15:37 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/2.Register.feature
> +	    |praveen					|mismatch	|Password confirmation must must match Password			|
this is resolved. rewrote steps in feature file.

2020-09-30 15:38 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/main/java/com/grails/pageObjects/RegisterPage.java
> +	Faker faker = new Faker();
created base test method and page extends this classes to resolve this issue.

2020-09-30 15:40 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/2.Register.feature
> +	    When user enter mailID and password "Fuller@123"
rewrote steps in scenario. My thought process was to use new mailID everytime to register user so I used faker plugin to generate new emailID everytime. For now, using  same email ID.

2020-09-30 15:42 UTC, jaiswalkpraveen commented on README.md
> +http://localhost:8080/WhatChaMaCallIt should be up and running
added instruction back and put automation read.md inside automation folder.

2020-09-30 15:45 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/java/com/grails/stepDefinitions/Hooks.java
> +	 	      final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
Yes, you can see failed screenshot attached in cucumber report below failed steps.

2020-09-30 16:15 UTC, dprski33 commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/1.Login.feature
> +   Scenario Outline: Login into application with invalid credential
So if we wanted to assert that the 'Login' button is disabled, could we do so with this case or would we need a different one?

2020-09-30 16:30 UTC, dprski33 commented on grailsUIAutomation/src/test/java/com/grails/stepDefinitions/Hooks.java
> +	 	      final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
I am currently getting the following error:
![image](https://user-images.githubusercontent.com/4399644/94713384-8ff44b00-02ff-11eb-9a33-4e9a77169ef5.png)

1. Please help resolve
2. Please tell me where i can find the screenshots

2020-09-30 17:36 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/resources/com.grails.functionalTests/1.Login.feature
> +   Scenario Outline: Login into application with invalid credential
I wrote this scenario a way that I should get validation error after clicking on login button. So I can add a script that if login button is not clickable I won't assert any message. To answer your question, yes we can with some changes in script.

2020-09-30 17:37 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/java/com/grails/stepDefinitions/Hooks.java
> +	 	      final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
Yes, I'm on it. Earlier issue was with driver.

2020-09-30 18:15 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/test/java/com/grails/stepDefinitions/Hooks.java
> +	 	      final byte[] screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
This should be resolved. Verified on friend MAC OS. I tried to pick webdriver based on OS but some issue in script.

2020-09-30 18:23 UTC, jaiswalkpraveen commented on grailsUIAutomation/configs/Configuration.properties
> +driverPath=src/test/resources/webdriver/
I created framework this way that chromedriver or any driver should reside inside it. Moving forward, if we execute it on CI pipeline or working in distributed team so  this could fail```driverPath=/usr/local/bin/chromedriver``` therefore they simply have to put driver inside webdriver folder. 
For now, I didn't implement firefox as it was increasing repo size by 16 MB. If you want, I can add it. I simply have to put 3 more line.

2020-09-30 18:27 UTC, jaiswalkpraveen commented
> In file `AutomatabilityLoginSuggestions.docs` you wrote:
> 
> > Allow alternate sign in option with third party social site
> 
> How does this suggestion make our application easier to automate?

My bad. I misunderstood automatability.

2020-09-30 18:30 UTC, jaiswalkpraveen commented on README.md
> +http://localhost:8080/WhatChaMaCallIt should be up and running
Wrote shell script to up the server but my script is unable to wait for server to be up and rather go to next command to start test suite. Figuring out a way to wait until application is up and running before triggering next cmd. Will push file once it get resolved.

2020-09-30 20:14 UTC, jaiswalkpraveen commented on grailsUIAutomation/src/main/java/com/grails/managers/WebDriverManager.java
> +	private WebDriver createDriver() {
I've used this in hooks file(line 22) to create an instance of driver. 
For now, I'm using Local driver and implemented the same. Moving forward, if I want to execute it with Selenium grid with diff OS and browser, we can implement RemoteWebDriver.

2020-10-03 16:17 UTC, closed without merging