Ui automation
JukinMediaInc/jukin-whatchamacallit pull request #6
Opened 2020-09-30 14:33 UTC by navendu-shukla

2020-09-30 16:44 UTC, dprski33 commented
This is what I get when I try to kick off the tests:
![image](https://user-images.githubusercontent.com/4399644/94714777-73591280-0301-11eb-906e-2c85dda91052.png)

2020-09-30 16:54 UTC, navendu-shukla commented
let me add the chrome driver for Mac.
Give me 10 mins. I will update you when I am done.

2020-09-30 16:59 UTC, dprski33 commented
I think I figured out the previous issue (I am using a Macbook, so `chromedriver.exe` will not execute for me). After making that change and kicking off the tests, I get this:
![image](https://user-images.githubusercontent.com/4399644/94714708-5cb2bb80-0301-11eb-9847-980f57ffb9db.png)

2020-09-30 17:02 UTC, navendu-shukla commented
No all the tests should not pass.
I have also automated the bugs which I found to showcase that scripts are effective

2020-10-01 19:24 UTC, dprski33 requested changes

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/README.txt
> +To execute all the UI tests execute : mvn clean verify -Dcucumber.options=--tags'@Login,@RegisterPage,@ForgotPassword'
wouldn't it be simpler to make all the tests run when there are no tags passed?

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/src/test/java/Utils/TestSessionInitiator.java
> +package Utils;
What changes would be needed to run the test suite against firefox, safari, IE?

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/LoginPageAction.java
> +		getUrl("http://localhost:8080/WhatChaMaCallIt/login");
If the app isn't running, is there anything you could do here to launch it?

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/src/test/java/Utils/TestSessionInitiator.java
> +package Utils;
Can this test suite be run against Firefox, Safari, IE?

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/README.txt
> +To execute all the UI tests execute : mvn clean verify -Dcucumber.options=--tags'@Login,@RegisterPage,@ForgotPassword'
wouldn't it be easier to run all the tests when there are no `tags` passed?

2020-10-01 19:24 UTC, dprski33 commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/RegisterPageAction.java
> +	public void verifySubmitButtonIsDisplayed() {
this method is also in `ForgotPasswordPageAction.java`. Is there a better way to organize your code so that the exact same method isn't needed for 2 different pages?

2020-10-01 20:40 UTC, navendu-shukla commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/LoginPageAction.java
> +		getUrl("http://localhost:8080/WhatChaMaCallIt/login");
Yes I could add a the script to run the command required to run the app.

I will add this as well in my next commit

2020-10-01 20:43 UTC, navendu-shukla commented on UI Automation Tests/README.txt
> +To execute all the UI tests execute : mvn clean verify -Dcucumber.options=--tags'@Login,@RegisterPage,@ForgotPassword'
We could do that. I just need to add the tags in the runner and when mvn clean verify command is executed whole test script will run.

Though I will not suggest it because using the tagging approach gives us flexibility to run a particular set of tests as well

2020-10-01 20:49 UTC, navendu-shukla commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/RegisterPageAction.java
> +	public void verifySubmitButtonIsDisplayed() {
This I will check I will remove this method both of them perform similar action.


I will add a commit for the changes suggested.
It is very late in night for me to make changes right away. I will make them by tomorrow evening

2020-10-02 21:31 UTC, navendu-shukla commented on UI Automation Tests/src/test/java/Utils/TestSessionInitiator.java
> +package Utils;
Added a commit with different browser configurations.

I did not had access to Mac machine so not verified the scripts for OS X. For browser compatibility testing across different os-browser configuration we normally use browserstack for execution.

2020-10-02 21:33 UTC, navendu-shukla commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/LoginPageAction.java
> +		getUrl("http://localhost:8080/WhatChaMaCallIt/login");
Added .bat and .sh files to run the app. Now at the time test initiation our app will also run

2020-10-02 21:33 UTC, navendu-shukla commented on UI Automation Tests/README.txt
> +To execute all the UI tests execute : mvn clean verify -Dcucumber.options=--tags'@Login,@RegisterPage,@ForgotPassword'
you can

2020-10-02 21:35 UTC, navendu-shukla commented on UI Automation Tests/README.txt
> +To execute all the UI tests execute : mvn clean verify -Dcucumber.options=--tags'@Login,@RegisterPage,@ForgotPassword'
you can use "mvn clean install" to run the tests.

2020-10-02 21:38 UTC, navendu-shukla commented on UI Automation Tests/src/test/java/JukinMedia/automation/action/RegisterPageAction.java
> +	public void verifySubmitButtonIsDisplayed() {
I checked the code. Both these methods perform different actions.
Here locator of the buttons are different even though they perform similar kind of action.
Added a suggestion to improve automatability regarding this as well

2020-10-03 18:10 UTC, closed without merging